### ISSUE TITLE
Docker Compose Option

### ISSUE THREAD

**Issue by BuddhiAbeyratne** [reclaim-the-stack/talos-manager#14]
I wanna add docker compose as a deployment option so people can use this interchangeably 

Customer rational - You can get a HA version of this running for less than 10 bucks with backups and under a firewall or even zerotrust and it will not require a Heroku account side quest. 

Dont mind doing the leg work if you guys are willing to take in outside contributions. Please do let me know what your contribution guidelines are.

**Comment by dbackeus** [comment]
I'd suggest forking and implementing this in a way that solves the problem for you guys. Then open a PR and we can take it from there.

I don't personally deploy anything using docker compose but I am very much open to adding deployment options. I also agree that the Heroku side quest isn't ideal.
