### ISSUE TITLE
Timeout issues when adding/editing cluster or conifg

### ISSUE THREAD

**Issue by goggi** [reclaim-the-stack/talos-manager#17]
Hey! Thanks for the nice tool! 

Just a FYI, I was having timeout issues when creating or editing clusters on the docker image. I went into the container and noticed that the talosctl command was running multiple times, and seems like it was stuck as it didn't exit.  
It works fine if I run it without docker tho!

**Comment by dbackeus** [comment]
Thanks for checking in!

Unfortunately I can't really do anything about it without a way to reproduce the issue.

Feel free to provide some steps to reproduce, including details of your hardware and OS etc and we can consider re-opening the issue.
