### ISSUE TITLE
Talos manager doesn't come up

### ISSUE THREAD

**Issue by gunnars04** [reclaim-the-stack/talos-manager#4]
Hi, I'm running through the Talos Manager tutorial again, and the app builds and deploys ok
But nothing comes up in the url (that I set previously in the HOST variable)
https://talos-manager-br.herokuapp.com/
And if I click the "open app" link in the Heroku dashboard, I get this link and a 403
https://talos-manager-br-f84bb46ed82a.herokuapp.com/
I did the tutorial 2x times (with different host names each time), and same result
My host url is correct
"heroku config:get HOST" gives me:
talos-manager-br.herokuapp.com 
![image](https://github.com/reclaim-the-stack/talos-manager/assets/10080542/f6fe8e69-4fce-445b-86d0-0d16bdf538e4)

If I go to:
https://talos-manager-br-f84bb46ed82a.herokuapp.com/
and do: "heroku logs --tail"
I get:
ERROR -- : [ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked host: talos-manager-br-f84bb46ed82a.herokuapp.com
And if I go to https://talos-manager-br.herokuapp.com/ I get nothing in the log. 
![image](https://github.com/reclaim-the-stack/talos-manager/assets/10080542/65f6104a-e154-4e05-a547-360dcdfebd69)

**Comment by dbackeus** [comment]
@gunnars04 kind of looks like it really expects `talos-manager-br-f84bb46ed82a.herokuapp.com` to be the host used. Does it work if you set `HOST=talos-manager-br-f84bb46ed82a.herokuapp.com` and use that as the domain?

Not sure why the suffix has been added to your app name. I'm assuming inside the Heroku UI that your app is named just `talos-manager-br`?

Maybe worth adding a custom domain and using your own host for more flexibility later on (eg. if you want to migrate `talos-manager` to another place in the future).

**Comment by gunnars04** [comment]
I think I found the reason for this:
https://devcenter.heroku.com/changelog-items/2597

No, it didn't help to change the host variable to the app domain url (I also deleted the app and re-created it). Gonna try the custom domain next.

**Comment by gunnars04** [comment]
@dbackeus Could you please try the first steps of the [readme ](https://github.com/reclaim-the-stack/talos-manager/blob/master/README.md) until after this step:
git push heroku
and see if you get reach your app at <name>.herokuapp.com? :)

**Comment by gunnars04** [comment]
Works now! 👍 
I just did all the steps in the readme
Got the error
Created an Azure App Service
Created a name/value pairs in Configuration -> Application settings
Restarted the service
Wollah!
![image](https://github.com/reclaim-the-stack/talos-manager/assets/10080542/b97ff0c6-d788-417a-9fc0-69c71fdb21f4)

**Comment by dbackeus** [comment]
For the record: Updated the documentation to support this new Heroku approach to subdomains in https://github.com/reclaim-the-stack/talos-manager/commit/bef536b035e57ff04557c83b53a2da64cb6d3590
