### ISSUE TITLE
Does the manager need to run after the cluster is ready?

### ISSUE THREAD

**Issue by treylade** [reclaim-the-stack/talos-manager#6]
First of all: Thank you very much for your work on this project and for releasing the information to the public.

I have one question: Does the manager need to keep running after the cluster is up and ready? Or may I shut it down to save compute costs and for security reasons. My idea is to just boot the manager whenever I need to change something.

Thank you and best regards,
Lars

**Comment by dbackeus** [comment]
Feel free to shut it down. The only time it needs to be running is when you want to use the UI or when a new node is requesting configuration to bootstrap itself.

Some kind of auto sleep / wake up based on incoming requests would probably be optimal, if possible.
